# Generated by Django 5.0.1 on 2024-03-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="symbol",
            old_name="compnay",
            new_name="company",
        ),
    ]
