# Generated by Django 5.0.1 on 2024-03-09 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0003_cache_stocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cache_stocks",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 9, 18, 10, 20, 417070, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
