# Generated by Django 5.0.1 on 2024-03-10 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0004_alter_cache_stocks_trading_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currencys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=30)),
                ("Country", models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name="cache_stocks",
            name="prev_price",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name="cache_stocks",
            name="price",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name="cache_stocks",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 10, 7, 39, 23, 349423, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
