# Generated by Django 5.0.1 on 2024-03-10 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0005_currencys_alter_cache_stocks_prev_price_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Currencys",
            new_name="Currency",
        ),
        migrations.AlterField(
            model_name="cache_stocks",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 10, 7, 41, 14, 488540, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
