# Generated by Django 5.0.1 on 2024-03-10 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0006_rename_currencys_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cache_currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prices", models.JSONField()),
                (
                    "trading_day",
                    models.DateField(
                        default=datetime.datetime(
                            2024, 3, 10, 11, 43, 9, 353216, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="cache_stocks",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 10, 11, 43, 9, 353216, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
