# Generated by Django 5.0.1 on 2024-03-10 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0007_cache_currency_alter_cache_stocks_trading_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cache_currency",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 10, 11, 54, 21, 933431, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cache_stocks",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 10, 11, 54, 21, 933431, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
