# Generated by Django 5.0.1 on 2024-03-11 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0008_alter_cache_currency_trading_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cache_stocks",
            name="prev_price",
        ),
        migrations.RemoveField(
            model_name="cache_stocks",
            name="price",
        ),
        migrations.RemoveField(
            model_name="cache_stocks",
            name="symbol",
        ),
        migrations.RemoveField(
            model_name="cache_stocks",
            name="volume",
        ),
        migrations.AddField(
            model_name="cache_stocks",
            name="prices",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cache_currency",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 11, 10, 5, 22, 988700, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cache_stocks",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 11, 10, 5, 22, 987690, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
