# Generated by Django 5.0.1 on 2024-03-11 10:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0009_remove_cache_stocks_prev_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cache_stocks",
            name="symbol",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="investment.symbol",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cache_currency",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 11, 10, 7, 49, 575838, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cache_stocks",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 11, 10, 7, 49, 575838, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
