# Generated by Django 5.0.1 on 2024-03-11 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "investment",
            "0010_cache_stocks_symbol_alter_cache_currency_trading_day_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cache_currency",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 11, 10, 12, 51, 61605, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cache_stocks",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 11, 10, 12, 51, 61605, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
