# Generated by Django 5.0.1 on 2024-03-11 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0011_alter_cache_currency_trading_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expensise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catagories", models.CharField(max_length=155)),
            ],
        ),
        migrations.AlterField(
            model_name="cache_currency",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 11, 21, 7, 9, 611504, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cache_stocks",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 11, 21, 7, 9, 610505, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
