# Generated by Django 5.0.1 on 2024-03-13 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0017_alter_cache_currency_trading_day_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="income_tracker",
            old_name="catagories",
            new_name="categories",
        ),
        migrations.RenameField(
            model_name="income_tracker",
            old_name="income_amount",
            new_name="revenue",
        ),
        migrations.AlterField(
            model_name="cache_currency",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 13, 8, 56, 2, 702621, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cache_stocks",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 13, 8, 56, 2, 701622, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="expenses_trackers",
            name="tracked_at",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 13, 8, 56, 2, 702830, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="income_tracker",
            name="tracked_at",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 13, 8, 56, 2, 703622, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
