# Generated by Django 5.0.1 on 2024-03-14 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0020_alter_cache_currency_trading_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cache_currency",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 14, 19, 23, 17, 82169, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cache_stocks",
            name="trading_day",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 14, 19, 23, 17, 81252, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="expenses_trackers",
            name="tracked_at",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 14, 19, 23, 17, 82169, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="goals",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 14, 19, 23, 17, 83168, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="income_tracker",
            name="tracked_at",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 14, 19, 23, 17, 83168, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
